---

services:
  
  ai-chatbot-rag:
    image: tonykay/ai-rag-chatbot:0.6.6
    container_name: chatbots
    hostname: chatbots
    volumes:
      - .:/app    # ,z
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
    environment:
      - "OLLAMA_BASE_URL=http://host.docker.internal:11434" 
    x-podman:
      uidmaps:
        - "1001:0:1"
        - "0:1:1001"
    restart: unless-stopped
